### ISSUE TITLE
[BUG] Error: dial tcp: lookup 10.100.0.13/24: no such host

### ISSUE THREAD

**Issue by SpiridonovVS** [danitso/terraform-provider-proxmox#6]
> proxmox_virtual_environment_file.k3os_server_cloud_config: Creating...
 proxmox_virtual_environment_file.k3os_server_cloud_config: Still creating... [10s elapsed]
 Error: dial tcp: lookup 10.100.0.13/24: no such host
   on 04-proxmox_vm_k3os.tf line 1, in resource "proxmox_virtual_environment_file" "k3os_server_cloud_config":
    1: resource "proxmox_virtual_environment_file" "k3os_server_cloud_config" {

...

> resource "proxmox_virtual_environment_file" "k3os_server_cloud_config" {
    content_type = "snippets"
    datastore_id = "cephfs-snippets"
    node_name    = "pve3"
    source_raw {
        data = <<EOF
EOF
    file_name = "terraform-k3os-server-cloud-config.yaml"
    }
}

**Comment by danitso-dp** [comment]
Hi @SpiridonovVS 

This feature is currently highly experimental but I believe the issue is how the provider tries to find the node's IP address. This is done by retrieving the list of network devices on the node and then grab the first IP address it can find. However, in your case, this results in a CIDR block instead.

Can you confirm whether the node is reachable on 10.100.0.13? We could use the hostname from the API endpoint instead even though this might cause conflicts with certain reverse proxies in the rare cases that people use one.

**Comment by danitso-dp** [comment]
Hi @SpiridonovVS 

Check out #8 in case the node can be reached on 10.100.0.13 as that small change should make it work. I'll await your feedback.

**Comment by SpiridonovVS** [comment]
Thx
