### ISSUE TITLE
[FEATURE] Publish to Terraform registry

### ISSUE THREAD

**Issue by ProfessorSalty** [danitso/terraform-provider-proxmox#66]
It would make my life easier if this provider were available on the [Terraform Registry](https://registry.terraform.io/) in two ways. The first is obviously just to make installation more convenient. More importantly than that, I'd like to use the [Cloud Development Kit for Terraform](https://learn.hashicorp.com/tutorials/terraform/cdktf) to simplify my homelab deployment onto Proxmox. From what I understand, nothing more is needed on the maintainers' part to make the provider compatible with cdktf than to just have it on the registry.

**Comment by danitso-dp** [comment]
@ProfessorSalty the provider will be published to the registry once v0.4.0 is released. I've sadly been busy with a lot of critical work lately which is why the release has been pending for a while. However, PR #61 is currently being tested to determine, if the various changes and improvements are stable. I'm planning to do my remaining testing by the end of this week so it can be released sometime next week.

**Comment by ProfessorSalty** [comment]
Brilliant. Thanks so much for your hard work! I'll close this.
